Algoritmo "semnome"
// Disciplina   : [segur e sist operaciponal]
// Professor   : bruno tulio
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : raika vieira nuneS & Josiel queiroz lima & maiara rodrigues macedo
// Data atual  : 08/09/2026
Var
// Seção de Declarações das variáveis 
 nome: caractere
idade: inteiro
altura: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
nome<- "raika & josiel & maiara"
idade<- 16
altura<- 1,70

Fimalgoritmo


